# Generated by Django 5.0.1 on 2024-03-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquizzes',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
