# Generated by Django 5.0.2 on 2024-03-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHunt',
            fields=[
                ('hunt_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('activity_type', models.CharField(max_length=100)),
                ('no_points', models.IntegerField()),
                ('information', models.TextField()),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.treasurehunt')),
            ],
            options={
                'unique_together': {('hunt', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_completed', models.BooleanField(default=False)),
                ('no_points', models.IntegerField()),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.treasurehunt')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.player')),
            ],
            options={
                'unique_together': {('hunt', 'player')},
            },
        ),
    ]
