<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-15 13:18
=======
# Generated by Django 5.0.2 on 2024-03-11 16:57
>>>>>>> aeaa74d99ce36db995297d3c93dc6463a24ec436

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Activities',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('info', models.TextField()),
                ('location', models.TextField()),
=======
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
>>>>>>> aeaa74d99ce36db995297d3c93dc6463a24ec436
            ],
        ),
        migrations.CreateModel(
            name='TreasureHunt',
            fields=[
                ('hunt_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.TextField(default='/img/Default.png')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('no_points', models.IntegerField()),
                ('information', models.TextField()),
                ('activity_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.activities')),
=======
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('activity_type', models.CharField(max_length=100)),
                ('no_points', models.IntegerField()),
                ('information', models.TextField()),
>>>>>>> aeaa74d99ce36db995297d3c93dc6463a24ec436
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.treasurehunt')),
            ],
            options={
                'unique_together': {('hunt', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('player', models.CharField(max_length=100)),
                ('stage_completed', models.BooleanField(default=False)),
                ('no_points', models.IntegerField()),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.treasurehunt')),
=======
                ('stage_completed', models.BooleanField(default=False)),
                ('no_points', models.IntegerField()),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.treasurehunt')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.player')),
>>>>>>> aeaa74d99ce36db995297d3c93dc6463a24ec436
            ],
            options={
                'unique_together': {('hunt', 'player')},
            },
        ),
    ]
