# Generated by Django 5.0.2 on 2024-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertreasure',
            name='player',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='treasurehunt',
            name='location',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
