# Generated by Django 5.0.2 on 2024-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='location_name',
            field=models.TextField(default='Parker moot room!'),
        ),
    ]
