# Generated by Django 5.0.3 on 2024-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_activities_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
