# Generated by Django 5.0.2 on 2024-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_alter_usertreasure_player_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slot',
            new_name='Stage',
        ),
        migrations.AddField(
            model_name='treasurehunt',
            name='name',
            field=models.CharField(default='TreasureHunt1', max_length=100),
        ),
    ]
