# Generated by Django 5.0.2 on 2024-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0003_rename_slot_stage_treasurehunt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurehunt',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
