# Generated by Django 5.0.2 on 2024-03-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0004_alter_treasurehunt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.TextField(default='/img/Default.png'),
        ),
    ]
