# Generated by Django 5.0.2 on 2024-03-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0005_stage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='image',
        ),
        migrations.AddField(
            model_name='treasurehunt',
            name='image',
            field=models.TextField(default='/img/Default.png'),
        ),
    ]
