# Generated by Django 5.0.2 on 2024-02-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
