# Generated by Django 5.0.3 on 2024-03-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizzes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='time',
            field=models.IntegerField(default=60),
        ),
    ]
