# Generated by Django 5.0.3 on 2024-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizzes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='time',
            field=models.IntegerField(default=60),
        ),
    ]
