# Generated by Django 5.0.3 on 2024-03-20 14:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamekeeper', '0002_dailyquizzes_time_limit'),
        ('quiz', '0006_alter_quizzes_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 3, 20, 14, 49, 18, 442320, tzinfo=datetime.timezone.utc))),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamekeeper.dailyquizzes')),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_quiz_id_points', to='quiz.quizzes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 3, 20, 14, 49, 18, 442320, tzinfo=datetime.timezone.utc))),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_id', to='quiz.quizzes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailypoints',
            constraint=models.UniqueConstraint(fields=('user_id', 'quiz_id', 'date'), name='composite_primary_key_2'),
        ),
        migrations.AddConstraint(
            model_name='points',
            constraint=models.UniqueConstraint(fields=('user_id', 'quiz_id'), name='composite_primary_key'),
        ),
    ]
