# Generated by Django 5.0.2 on 2024-03-15 12:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
        ('quiz', '0003_alter_quizzes_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 12, 57, 17, 96738, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AddField(
            model_name='points',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_id', to='quiz.quizzes'),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 12, 57, 17, 96738, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='points',
            constraint=models.UniqueConstraint(fields=('user_id', 'quiz_id'), name='composite_primary_key'),
        ),
        migrations.AddField(
            model_name='dailypoints',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_quiz_id_points', to='quiz.quizzes'),
        ),
        migrations.AddField(
            model_name='dailypoints',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailypoints',
            constraint=models.UniqueConstraint(fields=('user_id', 'quiz_id'), name='composite_primary_key_2'),
        ),
    ]
