# Generated by Django 5.0.1 on 2024-02-26 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_points_points_points_points_gained_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='points_gained',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 2, 26, 21, 54, 15, 722287, tzinfo=datetime.timezone.utc)),
        ),
    ]
