# Generated by Django 5.0.1 on 2024-02-27 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 21, 11, 44, 941368, tzinfo=datetime.timezone.utc)),
        ),
    ]
