# Generated by Django 5.0.1 on 2024-03-10 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 18, 45, 2, 380248, tzinfo=datetime.timezone.utc)),
        ),
    ]
