# Generated by Django 4.2.10 on 2024-03-11 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 17, 13, 13, 160460, tzinfo=datetime.timezone.utc)),
        ),
    ]
