<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-11 17:34
=======
# Generated by Django 4.2.10 on 2024-03-11 18:31
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 17, 34, 5, 427340, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 18, 31, 8, 98825, tzinfo=datetime.timezone.utc)),
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34
        ),
    ]
