# Generated by Django 5.0.2 on 2024-03-11 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0015_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 17, 44, 40, 43437, tzinfo=datetime.timezone.utc)),
        ),
    ]
