# Generated by Django 5.0.2 on 2024-03-11 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0016_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 18, 6, 43, 578873, tzinfo=datetime.timezone.utc)),
        ),
    ]
