# Generated by Django 5.0.2 on 2024-03-14 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 20, 29, 10, 958657, tzinfo=datetime.timezone.utc)),
        ),
    ]
