<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-14 20:29
=======
# Generated by Django 5.0.1 on 2024-03-12 21:41
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 20, 29, 10, 958657, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 21, 41, 6, 811392, tzinfo=datetime.timezone.utc)),
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34
        ),
    ]
