# Generated by Django 5.0.1 on 2024-03-12 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0018_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 22, 37, 40, 678880, tzinfo=datetime.timezone.utc)),
        ),
    ]
