<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-14 22:09
=======
# Generated by Django 5.0.1 on 2024-03-13 12:46
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0020_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 22, 9, 53, 234894, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 12, 46, 55, 533860, tzinfo=datetime.timezone.utc)),
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34
        ),
    ]
