<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-14 22:33
=======
# Generated by Django 5.0.1 on 2024-03-13 15:30
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0021_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 22, 33, 44, 426983, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 15, 30, 43, 120587, tzinfo=datetime.timezone.utc)),
>>>>>>> 9e0d04e7983be82afa3a3b0f71ff81002577ab34
        ),
    ]
