# Generated by Django 5.0.1 on 2024-03-13 23:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0022_alter_points_timestamp'),
        ('quiz', '0003_alter_quizzes_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 23, 11, 8, 224249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DailyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 3, 13, 23, 11, 8, 224249, tzinfo=datetime.timezone.utc))),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_quiz_id_points', to='quiz.quizzes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailypoints',
            constraint=models.UniqueConstraint(fields=('user_id', 'quiz_id'), name='composite_primary_key_2'),
        ),
    ]
