# Generated by Django 5.0.2 on 2024-03-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_dailypoints_points_quiz_id_alter_points_points_and_more'),
        ('points', '0023_alter_points_timestamp_dailypoints_and_more'),
    ]

    operations = [
    ]
