# Generated by Django 4.2.10 on 2024-03-15 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0023_alter_points_timestamp_dailypoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypoints',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 15, 23, 55, 490073, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 15, 23, 55, 489477, tzinfo=datetime.timezone.utc)),
        ),
    ]
