# Generated by Django 5.0.2 on 2024-03-15 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0024_merge_20240315_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypoints',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 13, 8, 54, 524376, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 13, 8, 54, 508753, tzinfo=datetime.timezone.utc)),
        ),
    ]
