<<<<<<< Updated upstream
# Generated by Django 5.0.3 on 2024-03-17 14:11
=======
# Generated by Django 5.0.1 on 2024-03-17 18:27
>>>>>>> Stashed changes

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0027_alter_dailypoints_timestamp_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypoints',
            name='timestamp',
<<<<<<< Updated upstream
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 14, 11, 11, 487922, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 18, 27, 48, 998113, tzinfo=datetime.timezone.utc)),
>>>>>>> Stashed changes
        ),
        migrations.AlterField(
            model_name='points',
            name='timestamp',
<<<<<<< Updated upstream
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 14, 11, 11, 487922, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 18, 27, 48, 998113, tzinfo=datetime.timezone.utc)),
>>>>>>> Stashed changes
        ),
    ]
