# Generated by Django 5.0.3 on 2024-03-19 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0029_alter_dailypoints_timestamp_alter_points_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypoints',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 59, 8, 970027, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 59, 8, 970027, tzinfo=datetime.timezone.utc)),
        ),
    ]
