# Generated by Django 5.0.1 on 2024-03-20 13:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0002_dailyquizzes_time_limit'),
        ('points', '0039_alter_dailypoints_timestamp_alter_points_timestamp'),
        ('quiz', '0006_alter_quizzes_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailypoints',
            name='composite_primary_key_2',
        ),
        migrations.AddField(
            model_name='dailypoints',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamekeeper.dailyquizzes'),
        ),
        migrations.AlterField(
            model_name='dailypoints',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 13, 40, 46, 438586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='points',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 13, 40, 46, 437584, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='dailypoints',
            constraint=models.UniqueConstraint(fields=('user_id', 'quiz_id', 'date'), name='composite_primary_key_2'),
        ),
    ]
