# Generated by Django 5.0.3 on 2024-03-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0040_alter_dailypoints_timestamp_alter_points_timestamp'),
        ('points', '0040_remove_dailypoints_composite_primary_key_2_and_more'),
    ]

    operations = [
    ]
